import type { Metadata } from 'next';
import Image from 'next/image'
import styles from './styles.module.css';
import head from '../head.svg'
import './global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header>
        <Image src={ head } alt='title'/>
        <div>
          <input className={ styles.searchField } type='text' />
          <input className={ styles.searchButton } type='button' value='Search' />
        </div>
      </header>
      <nav></nav>
      <main>
        { children }
      </main>
    </>
  );
}
